[package]
name = "pathtracer-rs"
version = "0.1.0"
authors = ["Eric Fang <eric1221bday@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.3"
anyhow = "^1.0"
env_logger = "^0.6"
log = "^0.4"
nalgebra-glm = "0.8.0"
nalgebra = "0.22.0"
genmesh = "^0.6"
image = "^0.22"
approx = "^0.3"
wgpu = "^0.5.0"
shaderc = "^0.6"
winit = "^0.22.2"
futures = "^0.3.5"
itertools = "^0.9.0"
clap = "^2.33"
num = "0.3.0"
rayon = "1.4.0"

[dependencies.indicatif]
version = "^0.15"
features = ["rayon"]

[dependencies.bytemuck]
version = "^1.3.1"
features = ["extern_crate_alloc"]

[dependencies.gltf]
version = "^0.13"